apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
  lables:
    app: daemon
spec:
  selector:
    matchLables:
      app: daemon
  template:
    metadata:
      lables:
        app: daemon
    spec: 
      containers:
        -name: daemon-container
        image: amazon/cloudwatch-agent
        ports:
          -containerport: 80