apiVersion: v1
kind: pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  affinity:
    nodeAuthority:
      preferredDuringsSchedulingIgnoreDuringExecution:
      -  weight: 80
         preference:
           matchExpression:
           - key: type
             operator: In
             values: 
             -  backend
  containers:
  - name: nginx-cont
    image: nginx:latest
    ports:
    - containerPort: 80