apiVersion: v1
kind:
metadata:
  name: np-pod
  lables:
    app: np
spec: 
  containers: 
    -name: tomcat-containers
    images: tomcat 10.1
    ports:
      -name: tomcat-port
      containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: np-svc
  lables:
    app: np
spec:
  type: Nodeport
  selector: 
    app: np
  ports:
    -name: tomcat-svc-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodeport: 30001